name: Auto-grading Tests

on:
  push:
    branches:
      - main  # Change this to your default branch name if different
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.19'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/test1.py --maxfail=1 --disable-warnings -q
          pytest tests/test2.py --maxfail=1 --disable-warnings -q
          pytest tests/test3.py --maxfail=1 --disable-warnings -q
